import 'package:flutter/material.dart';
import 'dart:math';

class AppState extends ChangeNotifier {
  // ==================== ESTADO GLOBAL ====================
  Color _backgroundColor = const Color(0xFF0F0B21);
  String _language = "Español";

  // Getters
  Color get backgroundColor => _backgroundColor;
  String get language => _language;

  // Setters con notificación
  void setBackgroundColor(Color color) {
    _backgroundColor = color;
    notifyListeners();
  }

  void setLanguage(String newLanguage) {
    if (_language != newLanguage &&
        ["Español", "Inglés", "Francés", "Coreano"].contains(newLanguage)) {
      _language = newLanguage;
      notifyListeners();
    }
  }

  void reset() {
    _backgroundColor = const Color(0xFF0F0B21);
    _language = "Español";
    notifyListeners();
  }

  // ==================== DICCIONARIO DE TEXTOS ====================
  static final Map<String, Map<String, String>> _dict = {
    "Español": {
      "titulo_juego": "EL\nIMPOSTOR",
      "jugar": "JUGAR",
      "manual": "CÓMO JUGAR",
      "ajustes": "AJUSTES",
      "detectar": "Aprende a detectar al infiltrado",
      "p1_t": "Prepara el Terreno",
      "p1_d": "Ajusta jugadores, impostores y categoría.",
      "p2_t": "Reparto de Roles",
      "p2_d": "Pasa el móvil. Todos ven la palabra, menos el impostor.",
      "p3_t": "Interrogatorio",
      "p3_d": "Da una pista. El impostor debe improvisar.",
      "p4_t": "El Veredicto",
      "p4_d": "Debaten y voten para desenmascarar al sospechoso.",
      "p5_t": "Victoria",
      "p5_d": "El pueblo gana si lo atrapa. El impostor si sobrevive.",
      "config_t": "CONFIGURACIÓN",
      "comenzar": "COMENZAR",
      "jugadores": "JUGADORES",
      "jugador": "Jugador",
      "escribe_nombres":
          "Escribe el nombre de cada jugador. Puedes dejarlo en blanco si prefieres.",
      "impostores": "IMPOSTORES",
      "impostor": "IMPOSTOR",
      "rondas": "RONDAS",
      "tema": "TEMÁTICA",
      "idioma": "IDIOMA",
      "reset": "RESTABLECER",
      "desc_jugadores": "Total de participantes",
      "desc_impostores": "¿Quién miente?",
      "desc_rondas": "Duración partida",
      "desc_tema": "Selecciona el mazo de palabras",
      "nota_adv_1": "Recomendamos al menos ",
      "nota_adv_2": " para una mejor experiencia.",
      "ALEATORIO": "ALEATORIO",
      "MAGIA": "MAGIA",
      "DEPORTES": "DEPORTES",
      "paso": "PASO",
      "de": "DE",
      "turno_de": "Es tu turno de ver el secreto",
      "toca_revelar": "TOCA PARA REVELAR",
      "privacidad_adv":
          "Asegúrate de que nadie más esté mirando la pantalla antes de tocar.",
      "eres_usuario": "ERES USUARIO",
      "eres_impostor_tit": "Eres el\nIMPOSTOR",
      "rol_secreto": "TU ROL SECRETO",
      "palabra_secreta_es": "LA PALABRA SECRETA ES",
      "no_muestres": "No muestres esta palabra a nadie",
      "inst_user":
          "Memoriza la palabra y pasa el dispositivo al siguiente jugador con cuidado.",
      "inst_imp": "Descubre la palabra secreta antes de que acaben las rondas.",
      "no_sospeche": "No dejes que nadie sospeche de ti.",
      "pasar_jugador": "Pasar al siguiente jugador",
      "ronda": "Ronda",
      "tiempo_restante": "TIEMPO RESTANTE",
      "imp_entre_vos":
          "El impostor está entre vosotros. Observa los gestos y haz preguntas clave.",
      "intentar_adivinar": "Intentar adivinar",
      "sig_ronda": "Siguiente ronda",
      "fase_final": "FASE FINAL",
      "cual_palabra": "¿Cuál era la palabra?",
      "inst_final":
          "Te han descubierto, pero aún puedes ganar. Si adivinas la palabra secreta, ¡la victoria es tuya!",
      "escribe_palabra": "Escribe la palabra secreta",
      "confirmar": "Confirmar",
      "imp_gano": "¡El Impostor ganó!",
      "pueblo_gano": "¡El Pueblo ganó!",
      "logro_pasar": "Lograron pasar desapercibidos",
      "palabra_era": "LA PALABRA SECRETA ERA",
      "imp_eran": "LOS IMPOSTORES ERAN",
      "jugar_otra": "Jugar otra vez",
      "volver_inicio": "Volver al inicio",
      "usuarios_ganaron": "¡Los usuarios ganaron!",
      "impostor_gano": "¡El Impostor ganó!",
      "usuarios_detectaron": "Los usuarios detectaron al impostor",
      "impostor_desapercibido": "El impostor pasó desapercibido",
      "palabra_secreta_era": "LA PALABRA SECRETA ERA",
      "los_impostores_eran": "LOS IMPOSTORES ERAN",
      "minutos": "MINUTOS",
      "impostor_label": "IMPOSTOR",
    },
    "Inglés": {
      "titulo_juego": "THE\nIMPOSTOR",
      "jugar": "PLAY",
      "manual": "HOW TO PLAY",
      "ajustes": "SETTINGS",
      "detectar": "Learn to detect the infiltrator",
      "p1_t": "Set the Stage",
      "p1_d": "Adjust players, impostors, and category.",
      "p2_t": "Role Distribution",
      "p2_d": "Everyone sees the word except the impostor.",
      "p3_t": "Interrogation",
      "p3_d": "Give a hint. The impostor must improvise.",
      "p4_t": "The Verdict",
      "p4_d": "Debate and vote to unmask the suspect.",
      "p5_t": "Victory",
      "p5_d": "Town wins if they catch him. Impostor if he survives.",
      "config_t": "CONFIGURATION",
      "comenzar": "START",
      "jugadores": "PLAYERS",
      "jugador": "Player",
      "escribe_nombres":
          "Write the name of each player. You can leave it blank if you prefer.",
      "impostores": "IMPOSTORS",
      "impostor": "IMPOSTOR",
      "rondas": "ROUNDS",
      "tema": "THEME",
      "idioma": "LANGUAGE",
      "reset": "RESET",
      "desc_jugadores": "Total participants",
      "desc_impostores": "Who is lying?",
      "desc_rondas": "Game duration",
      "desc_tema": "Select the word deck",
      "nota_adv_1": "We recommend at least ",
      "nota_adv_2": " for a better experience.",
      "ALEATORIO": "RANDOM",
      "MAGIA": "MAGIC",
      "DEPORTES": "SPORTS",
      "paso": "STEP",
      "de": "OF",
      "turno_de": "It's your turn to see the secret",
      "toca_revelar": "TAP TO REVEAL",
      "privacidad_adv":
          "Make sure no one else is looking at the screen before tapping.",
      "eres_usuario": "YOU ARE A CITIZEN",
      "eres_impostor_tit": "You are the\nIMPOSTOR",
      "rol_secreto": "YOUR SECRET ROLE",
      "palabra_secreta_es": "THE SECRET WORD IS",
      "no_muestres": "Do not show this word to anyone",
      "inst_user":
          "Memorize the word and pass the device to the next player carefully.",
      "inst_imp": "Find out the secret word before the rounds end.",
      "no_sospeche": "Don't let anyone suspect you.",
      "pasar_jugador": "Pass to next player",
      "ronda": "Round",
      "tiempo_restante": "TIME REMAINING",
      "imp_entre_vos":
          "The impostor is among you. Observe gestures and ask key questions.",
      "intentar_adivinar": "Try to guess",
      "sig_ronda": "Next round",
      "fase_final": "FINAL PHASE",
      "cual_palabra": "What was the word?",
      "inst_final":
          "You've been discovered, but you can still win. If you guess the secret word, victory is yours!",
      "escribe_palabra": "Type the secret word",
      "confirmar": "Confirm",
      "imp_gano": "The Impostor won!",
      "pueblo_gano": "The Town won!",
      "logro_pasar": "They managed to go unnoticed",
      "palabra_era": "THE SECRET WORD WAS",
      "imp_eran": "THE IMPOSTORS WERE",
      "jugar_otra": "Play again",
      "volver_inicio": "Back to start",
      "usuarios_ganaron": "The citizens won!",
      "impostor_gano": "The Impostor won!",
      "usuarios_detectaron": "The citizens detected the impostor",
      "impostor_desapercibido": "The impostor went unnoticed",
      "palabra_secreta_era": "THE SECRET WORD WAS",
      "los_impostores_eran": "THE IMPOSTORS WERE",
      "minutos": "MINUTES",
      "impostor_label": "IMPOSTOR",
    },
    "Francés": {
      "titulo_juego": "L'IMPOSTEUR",
      "jugar": "JOUER",
      "manual": "COMMENT JOUER",
      "ajustes": "PARAMÈTRES",
      "detectar": "Apprenez à détecter l'infiltré",
      "p1_t": "Préparez le Terrain",
      "p1_d": "Ajustez les joueurs, les imposteurs et la catégorie.",
      "p2_t": "Distribution des Rôles",
      "p2_d": "Tout le monde voit le mot, sauf l'imposteur.",
      "p3_t": "Interrogatoire",
      "p3_d": "Donnez un indice. L'imposteur doit improviser.",
      "p4_t": "Le Verdict",
      "p4_d": "Débattez et votez pour démasquer le suspect.",
      "p5_t": "Victoire",
      "p5_d": "Le village gagne s'il l'attrape.",
      "config_t": "CONFIGURATION",
      "comenzar": "COMMENCER",
      "jugadores": "JOUEURS",
      "jugador": "Joueur",
      "escribe_nombres":
          "Écrivez le nom de cada joueur. Vous pouvez le laisser vide si vous préférez.",
      "impostores": "IMPOSTEURS",
      "impostor": "IMPOSTEUR",
      "rondas": "TOURS",
      "tema": "THÈME",
      "idioma": "LANGUE",
      "reset": "RÉINITIALISER",
      "desc_jugadores": "Total de participants",
      "desc_impostores": "Qui ment ?",
      "desc_rondas": "Durée de la partie",
      "desc_tema": "Sélectionnez le jeu de mots",
      "nota_adv_1": "Nous recommandons au moins ",
      "nota_adv_2": " pour une meilleure expérience.",
      "ALEATORIO": "ALÉATOIRE",
      "MAGIA": "MAGIE",
      "DEPORTES": "SPORTS",
      "paso": "ÉTAPE",
      "de": "SUR",
      "turno_de": "C'est votre tour de voir le secret",
      "toca_revelar": "APPUYER POUR RÉVÉLER",
      "privacidad_adv":
          "Assurez-vous que personne d'autre ne regarde l'écran avant d'appuyer.",
      "eres_usuario": "VOUS ÊTES UN CITOYEN",
      "eres_impostor_tit": "Vous êtes\nL'IMPOSTEUR",
      "rol_secreto": "VOTRE RÔLE SECRET",
      "palabra_secreta_es": "LE MOT SECRET EST",
      "no_muestres": "Ne montrez ce mot à personne",
      "inst_user":
          "Mémorisez le mot et passez l'appareil au joueur suivant avec précaution.",
      "inst_imp": "Découvrez le mot secret avant la fin des tours.",
      "no_sospeche": "Ne laissez personne vous soupçonner.",
      "pasar_jugador": "Passer au joueur suivant",
      "ronda": "Tour",
      "tiempo_restante": "TEMPS RESTANT",
      "imp_entre_vos":
          "L'imposteur est parmi vous. Observez les gestes et posez des questions clés.",
      "intentar_adivinar": "Essayer de deviner",
      "sig_ronda": "Tour suivant",
      "fase_final": "PHASE FINALE",
      "cual_palabra": "Quel était le mot ?",
      "inst_final": "Vous avez été découvert, mais vous pouvez encore gagner.",
      "escrive_palabra": "Tapez le mot secret",
      "confirmar": "Confirmer",
      "imp_gano": "L'Imposteur a gagné !",
      "pueblo_gano": "Le Village a gagné !",
      "logro_pasar": "Ils ont réussi à passer inaperçus",
      "palabra_era": "LE MOT SECRET ÉTAIT",
      "imp_eran": "LES IMPOSTEURS ÉTAIENT",
      "jugar_otra": "Rejouer",
      "volver_inicio": "Retour au début",
      "usuarios_ganaron": "Les citoyens ont gagné !",
      "impostor_gano": "L'Imposteur a gagné !",
      "usuarios_detectaron": "Les citoyens ont détecté l'imposteur",
      "impostor_desapercibido": "L'imposteur est passé inaperçu",
      "palabra_secreta_era": "LE MOT SECRET ÉTAIT",
      "los_impostores_eran": "LES IMPOSTEURS ÉTAIENT",
      "minutos": "MINUTES",
      "impostor_label": "IMPOSTEUR",
    },
    "Coreano": {
      "titulo_juego": "임포스터",
      "jugar": "게임 시작",
      "manual": "게임 방법",
      "ajustes": "설정",
      "detectar": "잠입자를 찾는 방법 배우기",
      "p1_t": "준비하기",
      "p1_d": "플레이어 수, 임포스터 수, 카테고리를 설정하세요.",
      "p2_t": "역할 분배",
      "p2_d": "임포스터를 제외한 모두가 단어를 봅니다.",
      "p3_t": "심문",
      "p3_d": "힌트를 주세요. 임포스터는 즉흥적으로 답변해야 합니다.",
      "p4_t": "판결",
      "p4_d": "누가 거짓말을 하는지 토론하고 투표하세요.",
      "p5_t": "승리 조건",
      "p5_d": "임포스터를 잡으면 시민 승리.",
      "config_t": "환경 설정",
      "comenzar": "시작",
      "jugadores": "플레이어",
      "jugador": "플레이어",
      "escribe_nombres": "각 플레이어의 이름을 입력하세요. 원하는 경우 비워 둘 수 있습니다.",
      "impostores": "임포스터",
      "impostor": "임포스터",
      "rondas": "라운드",
      "tema": "배경 테마",
      "idioma": "언어",
      "reset": "초기화",
      "desc_jugadores": "총 참가자 수",
      "desc_impostores": "누가 거짓말을 하나요?",
      "desc_rondas": "게임 시간",
      "desc_tema": "단어 덱 선택",
      "nota_adv_1": "더 나은 경험을 위해 최소 ",
      "nota_adv_2": " 명의 플레이어를 권장합니다.",
      "ALEATORIO": "무작위",
      "MAGIA": "마법",
      "DEPORTES": "스포츠",
      "paso": "단계",
      "de": "/",
      "turno_de": "비밀을 확인할 차례입니다",
      "toca_revelar": "터치하여 확인하기",
      "privacidad_adv": "확인하기 전에 주변에 아무도 없는지 확인하세요.",
      "eres_usuario": "당신은 시민입니다",
      "eres_impostor_tit": "당신은\n임포스터입니다",
      "rol_secreto": "당신의 비밀 역할",
      "palabra_secreta_es": "비밀 단어는 다음과 같습니다",
      "no_muestres": "이 단어를 누구에게도 보여주지 마세요",
      "inst_user": "단어를 기억하고 다음 플레이어에게 조심스럽게 기기를 전달하세요.",
      "inst_imp": "라운드가 끝나기 전에 비밀 단어를 찾아내세요.",
      "no_sospeche": "아무도 당신을 의심하지 않게 하세요.",
      "pasar_jugador": "다음 플레이어에게 전달",
      "ronda": "라운드",
      "tiempo_restante": "남은 시간",
      "imp_entre_vos": "임포스터가 여러분 사이에 있습니다. 제스처를 관찰하세요.",
      "intentar_adivinar": "단어 맞추기",
      "sig_ronda": "다음 라운드",
      "fase_final": "마지막 단계",
      "cual_palabra": "단어는 무엇이었나요?",
      "inst_final": "정체가 탄로 났지만 아직 이길 수 있습니다.",
      "escribe_palabra": "비밀 단어를 입력하세요",
      "confirmar": "확인",
      "imp_gano": "임포스터 승리!",
      "pueblo_gano": "시민 승리!",
      "logro_pasar": "정체를 들키지 않고 성공했습니다",
      "palabra_era": "비밀 단어는",
      "imp_eran": "임포스터는",
      "jugar_otra": "다시 하기",
      "volver_inicio": "처음으로",
      "usuarios_ganaron": "시민들이 승리했습니다!",
      "impostor_gano": "임포스터가 승리했습니다!",
      "usuarios_detectaron": "시민들이 임포스터를 찾아냈습니다",
      "impostor_desapercibido": "임포스터가 들키지 않았습니다",
      "palabra_secreta_era": "비밀 단어는",
      "los_impostores_eran": "임포스터는",
      "minutos": "분",
      "impostor_label": "임포스터",
    },
  };

  String t(String key) {
    return _dict[_language]?[key] ?? _dict["Español"]?[key] ?? key;
  }

  // ==================== BANCO DE PALABRAS (wordDecks) ====================
  static const Map<String, Map<String, List<String>>> wordDecks = {
    "ALEATORIO": {
      "Español": [
        "AEROPUERTO",
        "PIZZA",
        "CEPILLO",
        "CINE",
        "PLAYA",
        "RELOJ",
        "GUITARRA",
        "ZAPATO",
        "MONTAÑA",
        "TELÉFONO",
        "CÁMARA",
        "BIBLIOTECA",
        "PANADERÍA",
        "BICICLETA",
        "ESPEJO",
        "LÁMPARA",
        "JARDÍN",
        "ASCENSOR",
        "PUENTE",
        "MUSEO",
        "HOSPITAL",
        "BOTELLA",
        "TECLADO",
        "ALMOHADA",
        "MICROONDAS",
        "MALETA",
        "ESTACIÓN",
        "LAGO",
        "BOSQUE",
        "RADIO",
      ],
      "Inglés": [
        "AIRPORT",
        "PIZZA",
        "BRUSH",
        "CINEMA",
        "BEACH",
        "WATCH",
        "GUITAR",
        "SHOE",
        "MOUNTAIN",
        "PHONE",
        "CAMERA",
        "LIBRARY",
        "BAKERY",
        "BICYCLE",
        "MIRROR",
        "LAMP",
        "GARDEN",
        "ELEVATOR",
        "BRIDGE",
        "MUSEUM",
        "HOSPITAL",
        "BOTTLE",
        "KEYBOARD",
        "PILLOW",
        "MICROWAVE",
        "SUITCASE",
        "STATION",
        "LAKE",
        "FOREST",
        "RADIO",
      ],
      "Francés": [
        "AÉROPORT",
        "PIZZA",
        "BROSSE",
        "CINÉMA",
        "PLAGE",
        "MONTRE",
        "GUITARE",
        "CHAUSSURE",
        "MONTAGNE",
        "TÉLÉPHONE",
        "APPAREIL PHOTO",
        "BIBLIOTHÈQUE",
        "BOULANGERIE",
        "BICYCLETTE",
        "MIROIR",
        "LAMPE",
        "JARDIN",
        "ASCENSEUR",
        "PONT",
        "MUSÉE",
        "HÔPITAL",
        "BOUTEILLE",
        "CLAVIER",
        "OREILLER",
        "MICRO-ONDES",
        "VALISE",
        "STATION",
        "LAC",
        "FORÊT",
        "RADIO",
      ],
      "Coreano": [
        "공항",
        "피자",
        "브러시",
        "영화관",
        "해변",
        "시계",
        "기타",
        "신발",
        "산",
        "전화기",
        "카메라",
        "도서관",
        "빵집",
        "자전거",
        "거울",
        "램프",
        "정원",
        "엘리베이터",
        "다리",
        "박물관",
        "병원",
        "병",
        "키보드",
        "베개",
        "전자레인지",
        "여행 가방",
        "역",
        "호수",
        "숲",
        "라디오",
      ],
    },
    "MAGIA": {
      "Español": [
        "VARITA",
        "CHAMPIÑÓN",
        "POCIÓN",
        "SOMBRERO",
        "CONEJO",
        "CARTAS",
        "CAPA",
        "ESCUDO",
        "HECHIZO",
        "DRAGÓN",
        "FÉNIX",
        "CRISTAL",
        "ANTORCHA",
        "CALDERO",
        "ESCOBA",
        "ALQUIMIA",
        "DUENDE",
        "AMULETO",
        "LABERINTO",
        "PERGAMINO",
        "ORÁCULO",
        "ESPEJISMO",
        "GRIMORIO",
        "TALISMÁN",
        "INVOCACIÓN",
        "PORTAL",
        "RITUAL",
        "ESTRELLA",
        "VARITA MÁGICA",
        "CENTAURO",
      ],
      "Inglés": [
        "WAND",
        "MUSHROOM",
        "POTION",
        "HAT",
        "RABBIT",
        "CARDS",
        "CAPE",
        "SHIELD",
        "SPELL",
        "DRAGON",
        "PHOENIX",
        "CRYSTAL",
        "TORCH",
        "CAULDRON",
        "BROOM",
        "ALCHEMY",
        "GOBLIN",
        "AMULET",
        "LABYRINTH",
        "SCROLL",
        "ORACLE",
        "MIRAGE",
        "GRIMOIRE",
        "TALISMAN",
        "SUMMONING",
        "PORTAL",
        "RITUAL",
        "STAR",
        "MAGIC WAND",
        "CENTAUR",
      ],
      "Francés": [
        "BAGUETTE",
        "CHAMPIGNON",
        "POTION",
        "CHAPEAU",
        "LAPIN",
        "CARTES",
        "CAPE",
        "BOUCLIER",
        "SORT",
        "DRAGON",
        "PHÉNIX",
        "CRISTAL",
        "TORCHE",
        "CHAUDRON",
        "BALAI",
        "ALCHIMIE",
        "LUTIN",
        "AMULETTE",
        "LABYRINTHE",
        "PARCHEMIN",
        "ORACLE",
        "MIRAGE",
        "GRIMOIRE",
        "TALISMAN",
        "INVOCATION",
        "PORTAIL",
        "RITUEL",
        "ÉTOILE",
        "BAGUETTE MAGIQUE",
        "CENTAURE",
      ],
      "Coreano": [
        "지팡이",
        "버섯",
        "포션",
        "모자",
        "토끼",
        "카드",
        "망토",
        "방패",
        "주문",
        "용",
        "불사조",
        "수정",
        "횃불",
        "가마솥",
        "빗자루",
        "연금술",
        "고블린",
        "부적",
        "미로",
        "두루마리",
        "오라클",
        "신기루",
        "마법서",
        "탈리스만",
        "소환",
        "포털",
        "의식",
        "별",
        "마법 지팡이",
        "켄타우로스",
      ],
    },
    "DEPORTES": {
      "Español": [
        "FÚTBOL",
        "TENIS",
        "NATACIÓN",
        "BALONCESTO",
        "GOLF",
        "BOXEO",
        "CICLISMO",
        "KARATE",
        "VOLEIBOL",
        "SURF",
        "ESQUÍ",
        "PATINAJE",
        "ATLETISMO",
        "BÉISBOL",
        "RUGBY",
        "HOCKEY",
        "MARATÓN",
        "ESGRIMA",
        "GIMNASIA",
        "BUCEO",
        "YOGA",
        "PADEL",
        "CRICKET",
        "BALONMANO",
        "MOTOCICLISMO",
        "TRIATLÓN",
        "SENDERISMO",
        "RAQUETA",
        "BALÓN",
        "ESTADIO",
      ],
      "Inglés": [
        "SOCCER",
        "TENNIS",
        "SWIMMING",
        "BASKETBALL",
        "GOLF",
        "BOXING",
        "CYCLING",
        "KARATE",
        "VOLLEYBALL",
        "SURFING",
        "SKIING",
        "SKATING",
        "ATHLETICS",
        "BASEBALL",
        "RUGBY",
        "HOCKEY",
        "MARATHON",
        "FENCING",
        "GYMNASTICS",
        "DIVING",
        "YOGA",
        "PADDLE",
        "CRICKET",
        "HANDBALL",
        "MOTORCYCLING",
        "TRIATHLON",
        "HIKING",
        "RACKET",
        "BALL",
        "STADIUM",
      ],
      "Francés": [
        "FOOTBALL",
        "TENNIS",
        "NATATION",
        "BASKETBALL",
        "GOLF",
        "BOXE",
        "CYCLISME",
        "KARATÉ",
        "VOLLEY-BALL",
        "SURF",
        "SKI",
        "PATINAGE",
        "ATHLÉTISME",
        "BASEBALL",
        "RUGBY",
        "HOCKEY",
        "MARATHON",
        "ESCRIME",
        "GYMNASTIQUE",
        "PLONGÉE",
        "YOGA",
        "PADDLE",
        "CRICKET",
        "HANDBALL",
        "MOTOCYCLISME",
        "TRIATHLON",
        "RANDONNÉE",
        "RAQUETTE",
        "BALLON",
        "STADE",
      ],
      "Coreano": [
        "축구",
        "테니스",
        "수영",
        "농구",
        "골프",
        "복싱",
        "사이클링",
        "가라데",
        "배구",
        "서핑",
        "스키",
        "스케이팅",
        "육상",
        "야구",
        "럭비",
        "하키",
        "마라톤",
        "펜싱",
        "체조",
        "다이빙",
        "요가",
        "패들",
        "크리켓",
        "핸드볼",
        "모터사이클링",
        "트라이애슬론",
        "하이킹",
        "라켓",
        "공",
        "경기장",
      ],
    },
  };

  // ====================== GENERAR PARTIDA ======================
  Map<String, dynamic> generateGame({
    required int totalPlayers,
    required int impostorsCount,
    required String theme,
    required String language,
    required int rounds,
  }) {
    var deck =
        (wordDecks[theme]?[language] ?? wordDecks["ALEATORIO"]![language]!)
            .toList();
    deck.shuffle(Random());

    final secretWord = deck[0];
    final impostorWord = deck.length > 1 ? deck[1] : deck[0];

    List<String> roles = List.generate(totalPlayers, (_) => "USER");
    List<int> indices = List.generate(totalPlayers, (i) => i)..shuffle();

    for (int i = 0; i < impostorsCount; i++) {
      if (i < indices.length) {
        roles[indices[i]] = "IMPOSTOR";
      }
    }

    return {
      "secretWord": secretWord,
      "impostorWord": impostorWord,
      "roles": roles,
      "theme": theme,
      "language": language,
      "rounds": rounds,
    };
  }
}
